### ISSUE TITLE
Error(s) in loading state_dict

### ISSUE THREAD

**Issue by DuyguSerbes** [Haichao-Zhang/FeatureScatter#6]
Thanks for the great job!

When I tried to use attached model, I have faced below error.

Error(s) in loading state_dict

RuntimeError: Error(s) in loading state_dict for Attack_PGD:
	Missing key(s) in state_dict: "basic_net.conv1.weight", "basic_net.block1.layer.0.bn1.weight",.......

The tensors already found in the checkpoint but my code gives error:

checkpoint = torch.load(resume_path)
start_epoch = checkpoint['epoch']
net.load_state_dict(checkpoint['net']

**Comment by Haichao-Zhang** [comment]
Could you give a try to wrap `net` with the following line and then try to load the state dict from the checkpoint again?
https://github.com/Haichao-Zhang/FeatureScatter/blob/a9c0eda20d01332712d83717dd85f289a82ab87f/fs_eval.py#L224

**Comment by Haichao-Zhang** [comment]
Please re-open the issue if you have further problems.
